### PR TITLE
Fixes #24492 - Fix serial console get disabled in host update

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by ShimShtein** [comment]
Don't we need to add also `wrap_attribute` line to [`update_vm`](https://github.com/fog/fog-ovirt/blob/07ccd5d4c35026d8a8384efe74b6a4bfa361661b/lib/fog/ovirt/requests/compute/v4/update_vm.rb#L27)?

@orrabin, shouldn't we introduce a model for console to make the interface more formal?

**Comment by shiramax** [comment]
@ShimShtein , Thanks 
I removed the href, please review again :)

**Comment by shiramax** [comment]
@ShimShtein can you please review again :)?

**Comment by shiramax** [comment]
@ShimShtein can you please review again :)?

**Review by ShimShtein — APPROVED** [review]

**Comment by ShimShtein** [comment]
@orrabin It's ready for merging. So unless we have some time considerations, we can merge it

**Comment by shiramax** [comment]
@orrabin can we merge this?

**Comment by orrabin** [comment]
Thanks @shiramax and @ShimShtein for reviewing!

**Pull request merged**
