### PR TITLE
Support storage domain lease and pass discard

### PR DESCRIPTION
**Pull request by zozoh94**
Support storage domain lease with HA VM and disk attachment pass discard

### CODE REVIEW

**Comment by zozoh94** [comment]
Hi ! Someone can explain me why Travis is failing ?

**Comment by shiramax** [comment]
@zozoh94 thanks for you PR!
this PR: https://github.com/fog/fog-ovirt/pull/69 should fix the rubocop errors.

**Review by shiramax — CHANGES_REQUESTED** [review]
@zozoh94 
I think it's better to wait until #69 will merge and then you will be able to rebase your PR.
Also, do you have a PR for foreman too?

**Comment by zozoh94** [comment]
@shiramax  As you want. I'll do the PR for Foreman when this one will be merged.

**Comment by shiramax** [comment]
@zozoh94 
We have a strict policy for adding oVirt features to Foreman, 
Because we can't have all oVirt features in Foreman,
Can you explain why do you need to support the leases? Why using templates it's not enough?

**Comment by JBaptisme** [comment]
Hello, I will try to explain benefit to add lease choice:
Lease is directly linked to High available. 
I think, a lease should be placed into first (bootable one for exemple) disk, if High available is checked.
I understand to use oVirt Template, but in this case, HA option should not be present in Foreman.

Moreover, Foreman provide good granularity regarding Storage Domain choice when provision VM, and not related to oVirt existing templates.
Lease is same think. It should be a list choice as Storage Domain. 
If chosen, Lease should be same as one of Storage Domain disk (preferably booting one)

Thanks for your time,

Regards

**Comment by shiramax** [comment]
@zozoh94 @JBaptisme 
 thanks for your comments, 
I still not sure I completely understand, 
can you create a template in ovirt that includes the properties you want? including the lease the ha part? 
and then create from that image a virtual machine in foreman?

**Comment by JBaptisme** [comment]
Hello @shiramax ,

Yes, It's possible to create a template into oVirt. 
But with ovirt template , it mean "Target Storage Domain for VM Lease" will be static ( it will be one of Storage domain, statically defined and that's all)...

If Target Storage Domain for VM Lease is available into Foreman, (like in oVirt template), it will be possible to choose destination storage domain for VM Lease for each Foreman VM created unlike template way.
For option Target Storage Domain for VM Lease , menu should me the same as Disk Storage domain

I hope It will be clearer ,

**Comment by shiramax** [comment]
thanks @zozoh94 @JBaptisme  :)
sounds ok to me, 
can you please explain about the discard? and also could you please add the foreman PR so I could test both together?

**Comment by erezzarum** [comment]
For some odd reason the lease does not inherit when using a template (at least a full clone one), just ran across this issue (oVirt 4.4) so it's either oVirt which should handle it or Foreman (uses fog)

**Pull request closed without merging**
