### PR TITLE
Add API V4 to Readme

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by ShimShtein** [comment]
LGTM, @iNecas, if you are OK with this, I'll merge.

**Review by ShimShtein — CHANGES_REQUESTED** [review]
Can you please add a small comment on how to choose between API V3 and V4?

**Comment by orrabin** [comment]
@ShimShtein I updated with an example, please review.

**Comment by iNecas** [comment]
Works for me, can we merge @ShimShtein?

**Review by ShimShtein — APPROVED** [review]

**Comment by ShimShtein** [comment]
Merged. 
Thanks @orrabin!

**Pull request merged**
