### PR TITLE
Include trimmed .travis.yml from fog/fog

### PR DESCRIPTION
**Pull request by adamruzicka**
I'm not sure about the notifications, do we need them at all?

### CODE REVIEW

**Comment by iNecas** [comment]
:-1: on notification

**Comment by iNecas** [comment]
Thanks, I guess we need to ask @orrabin to enable the travis hooks in the repo, but merging this one

**Comment by orrabin** [comment]
@geemus I don't have permissions in travis, could you please add this or add me so I can enable the repo?

**Comment by geemus** [comment]
@orrabin sure thing, I believe it should now be activated.

**Pull request merged**
