### PR TITLE
Fixes #26044 - Add VmType support for VM creation

### PR DESCRIPTION
**Pull request by bagasse**
Also updated `.rubocop_todo.yml` because it is annoying to see tests fail for that but I can remove this commit if wanted.

### CODE REVIEW

**Comment by UXabre** [comment]
This looks okay to me :-) @shiramax, what do you think? :-)

**Comment by bagasse** [comment]
Tested on foreman 1.22.x and oVirt 4.3.x

**Comment by shiramax** [comment]
@bagasse thanks, I created a PR for the rubocop errors: 
https://github.com/fog/fog-ovirt/pull/78
so, please remove it from your PR. 
@bagasse , I know I permised to release a new fog-ovirt version today, but I think it's better to release a new version later, once all the open PRs will merge.

**Comment by bagasse** [comment]
@shiramax, I removed the rubocop part. No problem for the release, it will be nice to get all current PR merged.

**Comment by shiramax** [comment]
@bagasse please rebase

**Comment by bagasse** [comment]
@shiramax, done.

**Review by shiramax — APPROVED** [review]

**Pull request merged**
