### PR TITLE
Change compute to Factory service and move current implementation to V3

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by shiramax** [comment]
@orrabin , I found a few issues:
1. I'm getting fog WARNING when trying to get all VMS of specific ComputeResource : 
irb(main):009:0* ComputeResource.first.vms
[fog][WARNING] Unrecognized arguments: ovirt_username, ovirt_password, ovirt_url, ovirt_datacenter, ovirt_ca_cert_store
2. When trying to provisioning host from compute resource image, I'm getting a validation requesting to add IP address, and after adding the IP address, next request in to add mac address. 

a few issues found that are not related to this specific change:
1. I created a compute profile, in the Cores and Memory sections I filled spaces, and the values that saved are   Cores=1 and Memory = 9 MB 
2. There is no validation error when filling a string in cores or memory.

I will open issues for the last two BZ.

**Comment by orrabin** [comment]
@shiramax thanks for testing, I'll look into the two related issues

**Comment by shiramax** [comment]
The issue for missing validation error : http://projects.theforeman.org/issues/22770

**Comment by orrabin** [comment]
@shiramax I fixed the warning but I was able to reproduce the validation without this pr so it's unrelated.
I opened a bug for it: http://projects.theforeman.org/issues/22788

**Comment by ShimShtein** [comment]
Played a bit with this PR: Opened foreman client and performed some readonly actions. It seems like foreman is behaving well with this pr. :+1:  from me, if @iNecas approves the code.

**Comment by iNecas** [comment]
No code related comments and the change makes sense with regard to adding v4 support. Thanks @orrabin, @ShimShtein and @shiramax

**Pull request merged**
