### PR TITLE
Fix rubocop 0.59 errors

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by iNecas** [comment]
Well, I feel quite strong against applying this rule. I think it actually hurts the readability. I understand there were good intentions when someone introduced this rule, but sometimes, the good intentions are just not enough :)

**Comment by orrabin** [comment]
I actually liked that one but it's a matter of personal preference and I agree it should stay that way so I'm disabling the cop.

**Comment by orrabin** [comment]
@iNecas could you take another look please?

**Comment by iNecas** [comment]
That looks better to me :) Thanks @orrabin

**Review by iNecas — APPROVED** [review]

**Pull request merged**
