### PR TITLE
Fixes #28030 - Add sockets support for instance_type

### PR DESCRIPTION
**Pull request by bagasse**

### CODE REVIEW

**Comment by bagasse** [comment]
Test failures are not related to this PR.

**Review by shiramax — CHANGES_REQUESTED** [review]
thanks @bagasse !
can you please open a redmine issue for this PR: 
https://projects.theforeman.org/projects/foreman/issues/new

when you finish, please change the commit message title to contain the prefix "Fixes #XXXX - "

**Comment by bagasse** [comment]
@shiramax, done.

**Comment by shiramax** [comment]
thanks @bagasse , that means you should add sockets  in sanitize_inherited_vm_attributes in foreman correct?

**Review by shiramax — APPROVED** [review]

**Comment by bagasse** [comment]
@shiramax, yes I will finish the work started in https://github.com/theforeman/foreman/pull/7070

**Comment by shiramax** [comment]
thanks @bagasse!

**Pull request merged**
