### PR TITLE
found missing exceptions, that were not handled by exception commit abf72242

### PR DESCRIPTION
**Pull request by ik5**

### CODE REVIEW

**Review by ShimShtein — CHANGES_REQUESTED** [review]
These tests were not triggered at all, we probably should modify them to run those lines or delete those lines altogether.

I think once we do that, we will have a better commit title on the way.

**Comment by orrabin** [comment]
@ik5 this needs a rebase

**Comment by ik5** [comment]
@ShimShtein i have made the changes, and the rebase again.

**Review by ShimShtein — APPROVED** [review]

**Comment by orrabin** [comment]
@ik5 the commit message is not very clear, please change to something like "remove redundant exception catching from test" or "remove ovirt exception from test and fix rubocop errors".

**Comment by ik5** [comment]
@orrabin the messaged was squashed, on the first push I noticed that I didn't squash it, so I'ved squashed it and pushed again.

**Comment by ik5** [comment]
Now I understand what you meant, I'ved updated the commit message, thank you.

**Comment by ShimShtein** [comment]
Merged. Thanks @ik5!

**Pull request merged**
