### PR TITLE
Use autoload

### PR DESCRIPTION
**Pull request by plribeiro3000**
This PR introduces the usage of `autoload` to load the constants.
This is a needed change because of fog/fog#3430

I've also move the files around to reflect the name conventions. A file named `Fog::Compute::Ovirt` is expected to be inside a file named `fog/compute/ovirt`. This will help newcomers to get to know your project easier.

### CODE REVIEW

**Comment by ShimShtein** [comment]
Can you please update the PR according to rubocop failures? Some files moved, so `.rubocop_todo.yml` needs update too.

**Comment by plribeiro3000** [comment]
Sure. Will do. =)

**Comment by plribeiro3000** [comment]
Done.

**Review by ShimShtein — COMMENTED** [review]
ACK from me, although it will require changes in specific requires:

``` diff
diff --git a/app/models/concerns/fog_extensions.rb b/app/models/concerns/fog_extensions.rb
index 56e9e3cf3..4b12af04d 100644
--- a/app/models/concerns/fog_extensions.rb
+++ b/app/models/concerns/fog_extensions.rb
@@ -32,12 +32,12 @@ end
 
 if Foreman::Model::Ovirt.available?
   require 'fog/ovirt'
-  require 'fog/ovirt/models/compute/server'
+  require 'fog/compute/ovirt/models/server'
   Fog::Compute::Ovirt::Server.send(:include, FogExtensions::Ovirt::Server)
-  require 'fog/ovirt/models/compute/template'
+  require 'fog/compute/ovirt/models/template'
   Fog::Compute::Ovirt::Template.send(:include, FogExtensions::Ovirt::Template)
 
-  require 'fog/ovirt/models/compute/volume'
+  require 'fog/compute/ovirt/models/volume'
   Fog::Compute::Ovirt::Volume.send(:include, FogExtensions::Ovirt::Volume)
 end
```
I have played with this a bit in Foreman, it seems to work once we change Foreman's code.

@orrabin, @iNecas, your call. I think it's major change and will require at least `.y` release.

**Comment by plribeiro3000** [comment]
@ShimShtein I did not know about this on foreman. Why do you guys explicit load the file? Why not just bundle it? Everything should be loaded right away when the gem is included by bundler.

**Comment by plribeiro3000** [comment]
Closing since the merge conflicts are too big

**Pull request closed without merging**
